# Generated by Django 3.0.3 on 2022-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=24, unique=True)),
                ('planet_type', models.CharField(default='NA', max_length=2)),
                ('home_star', models.CharField(max_length=24)),
                ('mass', models.DecimalField(decimal_places=10, max_digits=19)),
                ('radius', models.DecimalField(decimal_places=10, max_digits=19)),
                ('distance', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
